services:
  - type: web
    name: guest-checkin-api
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: ./data/database.sqlite
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
    healthCheckPath: /health
    
  - type: web
    name: guest-checkin-frontend
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: guest-checkin-api
          property: url
      - key: VITE_APP_TITLE
        value: Guest Check-in System
      - key: VITE_COMPANY_NAME
        value: Your Company Name
